### ISSUE TITLE
[Bug] Server Button Gone After Using Reload During Gameplay

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#665]
### Checklist

- [x] I will only use English in my report.
- [x] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### xCloud officially supports your country/region

Yes

### The bug doesn't happen when you disable Better xCloud script

Yes

### Previous Better xCloud versions didn't have this bug (name which one)

Yes

### Device

Other

### Device

NVIDIA Shield TV

### Operating System

Android TV 11

### Android app/Browser Version

0.22.3

### Better xCloud Version

6.4.1

### Reproduction Steps

Hi …

When you had to use the reload button to refresh the stream or apply settings during gameplay and then exit a game, the server button is not shown anymore on the home page.

It’s still possible to access the settings with the green button in the Guide menu, so the script is still running and active. Refreshing the home page brings the server button back again.

I think this didn’t happen before 6.4.1 and might be related to https://github.com/redphx/better-xcloud/commit/2fd482bb7bf21c5fb12a91f9a3ce1ffca45cd6c1 .

Thanks.

**Comment by redphx** [comment]
Fixed in 6.4.7

**Comment by KingNothing81** [comment]
Hi ...

Just checked after installing the update. And this still happens for me.

When you did a stream refresh during gameplay and then exit the game the "normal way" with the red button in the Guide menu, the server button is gone when returning to the home page.
